# AUTO-GENERATED by train/gen_enums.py — do not edit manually.
# Integer values/ordering come from the C++ enums in
# src/classes/action.h (ActionCategory) and src/classes/game.h (Step).
# Re-run train/gen_enums.py after changing either enum.

ACTION_CATEGORY_MAX = 26
N_ACTION_CATEGORIES = 27

# ActionCategory value -> short display name.
_CAT_NAMES = {
    0: "PASS",  # PASS_PRIORITY
    1: "MANA",  # MANA_ABILITY
    2: "SEL_ATK",  # SELECT_ATTACKER
    3: "CONF_ATK",  # CONFIRM_ATTACKERS
    4: "SEL_BLK",  # SELECT_BLOCKER
    5: "CONF_BLK",  # CONFIRM_BLOCKERS
    6: "ACTIVATE",  # ACTIVATE_ABILITY
    7: "CAST",  # CAST_SPELL
    8: "TARGET",  # SELECT_TARGET
    9: "LAND",  # PLAY_LAND
    10: "OTHER",  # OTHER_CHOICE
    11: "MULLIGAN",  # MULLIGAN
    12: "BOTTOM_CARD",  # BOTTOM_DECK_CARD
    13: "MANA_W",  # MANA_W
    14: "MANA_U",  # MANA_U
    15: "MANA_B",  # MANA_B
    16: "MANA_R",  # MANA_R
    17: "MANA_G",  # MANA_G
    18: "MANA_C",  # MANA_C
    19: "SEARCH",  # SEARCH_LIBRARY
    20: "TOP_LIB",  # TOP_LIBRARY
    21: "SHUFFLE",  # SHUFFLE
    22: "PAYING",  # PAYING_COSTS
    23: "DIG",  # DIG_CHOICE
    24: "SB_IN",  # SIDEBOARD_IN
    25: "SB_OUT",  # SIDEBOARD_OUT
    26: "SB_DONE",  # SIDEBOARD_DONE
}

# Step (turn phase) display names, in enum order.
_STEP_NAMES = [
    "Untap",  # UNTAP
    "Upkeep",  # UPKEEP
    "Draw",  # DRAW
    "First Main",  # FIRST_MAIN
    "Begin Combat",  # BEGIN_COMBAT
    "Declare Atk",  # DECLARE_ATTACKERS
    "Declare Blk",  # DECLARE_BLOCKERS
    "First Strike Dmg",  # FIRST_STRIKE_DAMAGE
    "Combat Dmg",  # COMBAT_DAMAGE
    "End Combat",  # END_OF_COMBAT
    "Second Main",  # SECOND_MAIN
    "End Step",  # END_STEP
    "Cleanup",  # CLEANUP
]

