# AUTO-GENERATED by train/gen_enums.py — do not edit manually.
# Integer values/ordering come from the C++ enums in
# src/classes/action.h (ActionCategory), src/classes/game.h (Step,
# MandatoryChoice), src/classes/gamestate.h (ActionRefZone), and the
# OBS_KEYWORDS array in src/machine_io.h.
# Re-run train/gen_enums.py after changing any of them.

ACTION_CATEGORY_MAX = 49
N_ACTION_CATEGORIES = 50

# ── Observation layout / size constants (parsed from the C++ headers, the
# single source of truth). train/env.py imports these instead of hand-
# copying the numbers; the header naming each constant follows it. ──
MAX_ACTIONS = 64  # src/classes/gamestate.h
MAX_CHOICE_DESC = 128  # src/classes/gamestate.h
PERM_COUNTERS_LEN = 64  # src/classes/gamestate.h
PERM_TOKEN_NAME_LEN = 32  # src/classes/gamestate.h
MAX_BATTLEFIELD_SLOTS = 48  # src/classes/gamestate.h
MAX_STACK_DISPLAY = 12  # src/classes/gamestate.h
MAX_STACK_MODES = 6  # src/classes/gamestate.h
MAX_STACK_TGTS = 4  # src/classes/gamestate.h
MAX_GY_SLOTS = 64  # src/classes/gamestate.h
MAX_HAND_SLOTS = 10  # src/classes/gamestate.h
DECKLIST_MAIN_SLOTS = 48  # src/classes/gamestate.h
DECKLIST_SIDE_SLOTS = 16  # src/classes/gamestate.h
KNOWN_TOP_LIBRARY_SIZE = 5  # src/classes/game.h
ACTION_HISTORY_SIZE = 128  # src/classes/game.h
STATE_SIZE = 6329  # src/machine_io.h
N_CARD_TYPES = 1024  # src/machine_io.h
PERM_SLOT_SIZE = 38  # src/machine_io.h
OPTION_ORDINAL_MAX = 63  # src/machine_io.h
N_ACTION_OBS_BLOCKS = 6  # src/machine_io.h
SIDEBOARD_SWAP_CAP = 15  # src/machine_io.h
PLAYER_BLOCK_SIZE = 10  # src/machine_io.h
STEP_ONEHOT_SIZE = 13  # src/machine_io.h
HEADER_FLAGS = 3  # src/machine_io.h
CARD_ID_SLOT_SIZE = 1  # src/machine_io.h
STACK_HEAD_FIELDS = 3  # src/machine_io.h
STACK_XAMT_FIELDS = 1  # src/machine_io.h
STACK_QUAL_FIELDS = 7  # src/machine_io.h
STACK_TGT_FIELDS = 5  # src/machine_io.h
HIST_ENTRY_SIZE = 4  # src/machine_io.h
MATCH_CTX_SIZE = 4  # src/machine_io.h
LIBRARY_CTX_SIZE = 3  # src/machine_io.h
CUR_TURN_SIZE = 1  # src/machine_io.h
PENDING_DECISION_SIZE = 2  # src/machine_io.h
EXTRAS_SCALARS = 13  # src/machine_io.h
EXTRAS_SB_CTX_SIZE = 3  # src/machine_io.h
DECKLIST_SLOT_SIZE = 2  # src/machine_io.h

# Name-keyed ActionCategory constants: CAT_<ENUM_NAME> = value, for every
# entry in the C++ ActionCategory enum (src/classes/action.h).
CAT_PASS_PRIORITY = 0
CAT_MANA_ABILITY = 1
CAT_SELECT_ATTACKER = 2
CAT_CONFIRM_ATTACKERS = 3
CAT_SELECT_BLOCKER = 4
CAT_CONFIRM_BLOCKERS = 5
CAT_ACTIVATE_ABILITY = 6
CAT_CAST_SPELL = 7
CAT_SELECT_TARGET = 8
CAT_PLAY_LAND = 9
CAT_OTHER_CHOICE = 10
CAT_MULLIGAN = 11
CAT_BOTTOM_DECK_CARD = 12
CAT_MANA_W = 13
CAT_MANA_U = 14
CAT_MANA_B = 15
CAT_MANA_R = 16
CAT_MANA_G = 17
CAT_MANA_C = 18
CAT_SEARCH_LIBRARY = 19
CAT_TOP_LIBRARY = 20
CAT_SHUFFLE = 21
CAT_PAYING_COSTS = 22
CAT_DIG_CHOICE = 23
CAT_SIDEBOARD_IN = 24
CAT_SIDEBOARD_OUT = 25
CAT_SIDEBOARD_DONE = 26
CAT_SACRIFICE_PERMANENT = 27
CAT_RETURN_PERMANENT = 28
CAT_CHOOSE_X = 29
CAT_DISCARD = 30
CAT_CHOOSE_MODE = 31
CAT_CHOOSE_MANA_COLOR = 32
CAT_PAY_UNLESS = 33
CAT_NAME_CARD = 34
CAT_CHOOSE_TYPE = 35
CAT_KEEP_LEGEND = 36
CAT_ORDER_TRIGGERS = 37
CAT_CHOOSE_REPLACEMENT = 38
CAT_ATTACK_TARGET = 39
CAT_BLOCK_TARGET = 40
CAT_OPTIONAL_YESNO = 41
CAT_PLAY_FREE = 42
CAT_SYLVAN_CHOICE = 43
CAT_CHOOSE_CARD = 44
CAT_ASSIGN_DAMAGE = 45
CAT_COMPANION = 46
CAT_DONT_SHUFFLE = 47
CAT_KEEP_HAND = 48
CAT_EXILE_FROM_YARD = 49

# ActionCategory value -> short display name.
_CAT_NAMES = {
    0: "PASS",  # PASS_PRIORITY
    1: "MANA",  # MANA_ABILITY
    2: "SEL_ATK",  # SELECT_ATTACKER
    3: "CONF_ATK",  # CONFIRM_ATTACKERS
    4: "SEL_BLK",  # SELECT_BLOCKER
    5: "CONF_BLK",  # CONFIRM_BLOCKERS
    6: "ACTIVATE",  # ACTIVATE_ABILITY
    7: "CAST",  # CAST_SPELL
    8: "TARGET",  # SELECT_TARGET
    9: "LAND",  # PLAY_LAND
    10: "OTHER",  # OTHER_CHOICE
    11: "MULLIGAN",  # MULLIGAN
    12: "BOTTOM_CARD",  # BOTTOM_DECK_CARD
    13: "MANA_W",  # MANA_W
    14: "MANA_U",  # MANA_U
    15: "MANA_B",  # MANA_B
    16: "MANA_R",  # MANA_R
    17: "MANA_G",  # MANA_G
    18: "MANA_C",  # MANA_C
    19: "SEARCH",  # SEARCH_LIBRARY
    20: "TOP_LIB",  # TOP_LIBRARY
    21: "SHUFFLE",  # SHUFFLE
    22: "PAYING",  # PAYING_COSTS
    23: "DIG",  # DIG_CHOICE
    24: "SB_IN",  # SIDEBOARD_IN
    25: "SB_OUT",  # SIDEBOARD_OUT
    26: "SB_DONE",  # SIDEBOARD_DONE
    27: "SACRIFICE",  # SACRIFICE_PERMANENT
    28: "RETURN",  # RETURN_PERMANENT
    29: "CHOOSE_X",  # CHOOSE_X
    30: "DISCARD",  # DISCARD
    31: "MODE",  # CHOOSE_MODE
    32: "MANA_COLOR",  # CHOOSE_MANA_COLOR
    33: "PAY_UNLESS",  # PAY_UNLESS
    34: "NAME_CARD",  # NAME_CARD
    35: "CHOOSE_TYPE",  # CHOOSE_TYPE
    36: "KEEP_LEGEND",  # KEEP_LEGEND
    37: "ORDER_TRIG",  # ORDER_TRIGGERS
    38: "REPLACE",  # CHOOSE_REPLACEMENT
    39: "ATK_TGT",  # ATTACK_TARGET
    40: "BLK_TGT",  # BLOCK_TARGET
    41: "YES_NO",  # OPTIONAL_YESNO
    42: "PLAY_FREE",  # PLAY_FREE
    43: "SYLVAN",  # SYLVAN_CHOICE
    44: "CHOOSE_CARD",  # CHOOSE_CARD
    45: "ASSIGN_DMG",  # ASSIGN_DAMAGE
    46: "COMPANION",  # COMPANION
    47: "DONT_SHUFFLE",  # DONT_SHUFFLE
    48: "KEEP_HAND",  # KEEP_HAND
    49: "EXILE_FROM_YARD",  # EXILE_FROM_YARD
}

# Step (turn phase) display names, in enum order.
_STEP_NAMES = [
    "Untap",  # UNTAP
    "Upkeep",  # UPKEEP
    "Draw",  # DRAW
    "First Main",  # FIRST_MAIN
    "Begin Combat",  # BEGIN_COMBAT
    "Declare Atk",  # DECLARE_ATTACKERS
    "Declare Blk",  # DECLARE_BLOCKERS
    "First Strike Dmg",  # FIRST_STRIKE_DAMAGE
    "Combat Dmg",  # COMBAT_DAMAGE
    "End Combat",  # END_OF_COMBAT
    "Second Main",  # SECOND_MAIN
    "End Step",  # END_STEP
    "Cleanup",  # CLEANUP
]

N_MANDATORY_CHOICES = 6

# MandatoryChoice display names, in enum order (the one-hot in the
# state vector's global-extras block; NONE is a real slot at index 0).
_MC_NAMES = [
    "None",  # NONE
    "Declare Atk",  # DECLARE_ATTACKERS_CHOICE
    "Declare Blk",  # DECLARE_BLOCKERS_CHOICE
    "Cleanup Discard",  # CLEANUP_DISCARD
    "Choose Entity",  # CHOOSE_ENTITY
    "Assign Dmg",  # ASSIGN_COMBAT_DAMAGE_CHOICE
]

N_OBS_KEYWORDS = 16

# Per-permanent keyword multi-hot vocabulary, in serialized order
# (mirrors OBS_KEYWORDS in src/machine_io.h).
_OBS_KEYWORDS = [
    "Flying",
    "Reach",
    "First Strike",
    "Double Strike",
    "Deathtouch",
    "Lifelink",
    "Trample",
    "Vigilance",
    "Menace",
    "Haste",
    "Defender",
    "Indestructible",
    "Hexproof",
    "Shroud",
    "Ward",
    "Flash",
]

REF_ZONE_MAX = 11
N_REF_ZONES = 12

# ActionRefZone value -> short display name (per-action zone_ref block).
_REF_NAMES = {
    0: "-",  # REF_NONE
    1: "own bf",  # REF_SELF_BATTLEFIELD
    2: "opp bf",  # REF_OPP_BATTLEFIELD
    3: "hand",  # REF_SELF_HAND
    4: "opp hand",  # REF_OPP_HAND
    5: "stack",  # REF_STACK
    6: "own gy",  # REF_SELF_GY
    7: "opp gy",  # REF_OPP_GY
    8: "own ex",  # REF_SELF_EXILE
    9: "opp ex",  # REF_OPP_EXILE
    10: "you",  # REF_PLAYER_SELF
    11: "opp",  # REF_PLAYER_OPP
}

