# AUTO-GENERATED by train/gen_card_costs.py — do not edit manually.
# Re-run after updating src/card_vocab.h or card script files.
import numpy as np

N_CARD_TYPES = 32
_N_COST_FEATS = 7  # W, U, B, R, G, C, generic (pip counts / 10.0)

_CARD_COST_MATRIX = np.array([
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 0: Mountain
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 1: Forest
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0],  # 2: Lightning Bolt
    [0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.1],  # 3: Grizzly Bears
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 4: Volcanic Island
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 5: Scalding Tarn
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 6: Flooded Strand
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 7: Polluted Delta
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 8: Wooded Foothills
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 9: Misty Rainforest
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 10: Wasteland
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 11: Ponder
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.3],  # 12: Force of Will
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.1],  # 13: Daze
    [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 14: Soul Warden
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 15: Tundra
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 16: Delver of Secrets
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 17: Insectile Aberration
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 18: Flying Men
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 19: Island
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0],  # 20: Dragon's Rage Channeler
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.3],  # 21: Air Elemental
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0],  # 22: Counterspell
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.1],  # 23: Lightning Strike
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 24: Brainstorm
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 25: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 26: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 27: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 28: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 29: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 30: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 31: 
], dtype=np.float32)

# Populated manually when non-mana activated abilities are added.
_CARD_ABILITY_COST_MATRIX = np.zeros((N_CARD_TYPES, _N_COST_FEATS), dtype=np.float32)
