# AUTO-GENERATED by train/gen_card_costs.py — do not edit manually.
# Re-run after updating src/card_vocab.h or card script files.
import numpy as np

N_CARD_TYPES = 32
_N_COST_FEATS = 7  # W, U, B, R, G, C, generic (pip counts / 10.0)

_CARD_COST_MATRIX = np.array([
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 0: Mountain
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 1: Forest
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0],  # 2: Lightning Bolt
    [0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.1],  # 3: Grizzly Bears
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 4: Volcanic Island
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 5: Scalding Tarn
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 6: Flooded Strand
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 7: Polluted Delta
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 8: Wooded Foothills
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 9: Misty Rainforest
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 10: Wasteland
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 11: Ponder
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.3],  # 12: Force of Will
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.1],  # 13: Daze
    [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 14: Soul Warden
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 15: Tundra
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 16: Delver of Secrets
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 17: Insectile Aberration
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 18: Flying Men
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 19: Island
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0],  # 20: Dragon's Rage Channeler
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.3],  # 21: Air Elemental
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0],  # 22: Counterspell
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.1],  # 23: Lightning Strike
    [0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0],  # 24: Brainstorm
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 25: Thundering Falls
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.5],  # 26: Murktide Regent
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 27: Mishra's Bauble
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 28: Cori-Steel Cutter
    [0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0],  # 29: Unholy Heat
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 30: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # 31: 
], dtype=np.float32)

# Populated manually when non-mana activated abilities are added.
_CARD_ABILITY_COST_MATRIX = np.zeros((N_CARD_TYPES, _N_COST_FEATS), dtype=np.float32)

# Index → card name, mirrors card_vocab.h
_VOCAB_NAMES = [
    "Mountain",  # 0
    "Forest",  # 1
    "Lightning Bolt",  # 2
    "Grizzly Bears",  # 3
    "Volcanic Island",  # 4
    "Scalding Tarn",  # 5
    "Flooded Strand",  # 6
    "Polluted Delta",  # 7
    "Wooded Foothills",  # 8
    "Misty Rainforest",  # 9
    "Wasteland",  # 10
    "Ponder",  # 11
    "Force of Will",  # 12
    "Daze",  # 13
    "Soul Warden",  # 14
    "Tundra",  # 15
    "Delver of Secrets",  # 16
    "Insectile Aberration",  # 17
    "Flying Men",  # 18
    "Island",  # 19
    "Dragon's Rage Channeler",  # 20
    "Air Elemental",  # 21
    "Counterspell",  # 22
    "Lightning Strike",  # 23
    "Brainstorm",  # 24
    "Thundering Falls",  # 25
    "Murktide Regent",  # 26
    "Mishra's Bauble",  # 27
    "Cori-Steel Cutter",  # 28
    "Unholy Heat",  # 29
    "",  # 30
    "",  # 31
]
