#!/usr/bin/env python3
"""
Run from repo root after editing train/sb_dead_rules.json (or when card
scripts / src/card_vocab.h change):
    python train/gen_sb_rules.py

Compiles the hand-edited dead-sideboard-card rules table into the two
generated data files the shared "prune dead INs" evaluator reads:

    train/sb_rules.py       (Python side: mcts.sb_dead_mask)
    src/gen/sb_rules_gen.h  (C++ twin:   src/actor/sb_rules.h)

Both are UNTRACKED and regenerated every `make` (like card_costs_gen.h): the
fact bits derive from card-script CONTENT via gen_card_props.build_matrix, and
scripts are gitignored. Emits DATA ONLY - the evaluator logic is hand-mirrored
between train/mcts.py and src/actor/sb_rules.h (menu_merge precedent).

Encoding: one fixed 17-column fact layout (SB_FACT_COLS - colors, basic land
subtypes, card types; NEVER reordered, so editing the JSON can't shift bit
meanings), each card's facts packed into one uint32 bitmask, each rule a
(card_vocab_id, condition_mask) pair. An IN of a ruled card is dead iff no
card of the opponent's registered 75 has any condition bit set.

A rule naming a card absent from src/card_vocab.h, or a condition with an
unknown key/value, is a hard error. `pending_review` entries are ignored.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_card_costs import REPO_ROOT, VOCAB_H, N_TYPES, parse_vocab
from gen_card_props import COL, build_matrix
from gen_util import write_if_changed

RULES_JSON = os.path.join(REPO_ROOT, "train/sb_dead_rules.json")
OUT_PY = os.path.join(REPO_ROOT, "train/sb_rules.py")
OUT_HEADER = os.path.join(REPO_ROOT, "src/gen/sb_rules_gen.h")

# Fixed fact-column layout (bit i of a facts mask = column i). Load-bearing
# order shared with the C++ header; append-only.
SB_FACT_COLS = [
    "color_w", "color_u", "color_b", "color_r", "color_g",
    "land_plains", "land_island", "land_swamp", "land_mountain", "land_forest",
    "type_artifact", "type_enchantment", "type_creature", "type_land",
    "type_instant", "type_sorcery", "type_planeswalker",
]

_COLOR_BIT = {"W": 0, "U": 1, "B": 2, "R": 3, "G": 4}
_SUBTYPE_BIT = {"plains": 5, "island": 6, "swamp": 7, "mountain": 8,
                "forest": 9}
_TYPE_BIT = {"artifact": 10, "enchantment": 11, "creature": 12, "land": 13,
             "instant": 14, "sorcery": 15, "planeswalker": 16}


def condition_bit(cond):
    """One condition object -> its fact-bit index (hard error on unknowns)."""
    if not isinstance(cond, dict) or len(cond) != 1:
        raise SystemExit(f"sb_dead_rules: malformed condition {cond!r}")
    (key, val), = cond.items()
    if key == "color":
        bit = _COLOR_BIT.get(str(val).upper())
    elif key == "land_subtype":
        bit = _SUBTYPE_BIT.get(str(val).lower())
    elif key == "card_type":
        bit = _TYPE_BIT.get(str(val).lower())
    else:
        raise SystemExit(f"sb_dead_rules: unknown condition key {key!r}")
    if bit is None:
        raise SystemExit(f"sb_dead_rules: unknown {key} value {val!r}")
    return bit


def main():
    with open(RULES_JSON) as f:
        table = json.load(f)
    vocab = parse_vocab(VOCAB_H)
    lower_vocab = {n.lower(): i for n, i in vocab.items()}
    matrix = build_matrix(vocab)

    facts = [0] * N_TYPES
    for idx in range(N_TYPES):
        m = 0
        for bit, col_name in enumerate(SB_FACT_COLS):
            if matrix[idx][COL[col_name]] > 0.0:
                m |= 1 << bit
        facts[idx] = m

    rules = []  # (card_id, mask, card_name, desc)
    for rule in table.get("rules", []):
        name = rule["card"]
        idx = lower_vocab.get(name.lower())
        if idx is None:
            raise SystemExit(
                f"sb_dead_rules: card {name!r} not in src/card_vocab.h")
        conds = rule["dead_unless_opp_has"]
        if isinstance(conds, dict):
            conds = [conds]
        mask = 0
        descs = []
        for c in conds:
            bit = condition_bit(c)
            mask |= 1 << bit
            descs.append(SB_FACT_COLS[bit])
        rules.append((idx, mask, name, " | ".join(descs)))
    rules.sort()
    dup = {i for n, (a, _, _, _) in enumerate(rules)
           for (b, _, _, _) in rules[n + 1:] if (i := a) == b}
    if dup:
        raise SystemExit(f"sb_dead_rules: duplicate rules for card ids {dup}")
    print(f"sb rules: {len(rules)} rules, "
          f"{len(table.get('pending_review', []))} pending_review "
          f"(ignored), {len(SB_FACT_COLS)} fact columns")

    vocab_by_idx = {i: n for n, i in vocab.items()}

    # --- Python module -----------------------------------------------------
    py = [
        "# AUTO-GENERATED by train/gen_sb_rules.py - do not edit manually.",
        "# Edit train/sb_dead_rules.json instead; regenerated every `make`.",
        "# Data only: the evaluator is mcts.sb_dead_mask (hand-mirrored with",
        "# src/actor/sb_rules.h).",
        "",
        "# Bit i of a facts mask corresponds to SB_FACT_COLS[i].",
        "SB_FACT_COLS = [",
    ]
    for c in SB_FACT_COLS:
        py.append(f'    "{c}",')
    py += [
        "]",
        "",
        "# card_vocab_id -> condition mask. An IN of this card is dead iff no",
        "# card of the opponent's registered 75 has any of these fact bits.",
        "SB_DEAD_RULES = {",
    ]
    for idx, mask, name, desc in rules:
        py.append(f"    {idx}: 0x{mask:05x},  # {name}: needs {desc}")
    py += [
        "}",
        "",
        "# card_vocab_id -> fact bitmask over SB_FACT_COLS.",
        "SB_CARD_FACTS = [",
    ]
    for idx in range(N_TYPES):
        comment = vocab_by_idx.get(idx, "")
        tail = f"  # {idx}: {comment}" if comment else ""
        py.append(f"    0x{facts[idx]:05x},{tail}")
    py += ["]", ""]
    write_if_changed(OUT_PY, "\n".join(py) + "\n")
    print(f"Wrote {OUT_PY}")

    # --- C++ header --------------------------------------------------------
    h = [
        "// AUTO-GENERATED by train/gen_sb_rules.py - do not edit manually.",
        "// Edit train/sb_dead_rules.json instead; regenerated every `make`.",
        "// Data only: the evaluator is src/actor/sb_rules.h (hand-mirrored",
        "// with mcts.sb_dead_mask in train/mcts.py).",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"static constexpr int N_SB_FACT_COLS = {len(SB_FACT_COLS)};",
        f"static constexpr int N_SB_DEAD_RULES = {len(rules)};",
        "",
        "// Sorted ascending by card id (binary-search friendly).",
        f"static constexpr int32_t SB_RULE_CARD[{max(len(rules), 1)}] = {{",
    ]
    for idx, mask, name, desc in rules:
        h.append(f"    {idx},  // {name}")
    if not rules:
        h.append("    -1,  // no rules")
    h += [
        "};",
        f"static constexpr uint32_t SB_RULE_MASK[{max(len(rules), 1)}] = {{",
    ]
    for idx, mask, name, desc in rules:
        h.append(f"    0x{mask:05x},  // {name}: needs {desc}")
    if not rules:
        h.append("    0,")
    h += [
        "};",
        "",
        "// card_vocab_id -> fact bitmask (bit order = gen_sb_rules.py's",
        "// SB_FACT_COLS).",
        f"static constexpr uint32_t SB_CARD_FACTS[{N_TYPES}] = {{",
    ]
    for idx in range(N_TYPES):
        comment = vocab_by_idx.get(idx, "")
        tail = f"  // {idx}: {comment}" if comment else ""
        h.append(f"    0x{facts[idx]:05x},{tail}")
    h += ["};", ""]
    write_if_changed(OUT_HEADER, "\n".join(h) + "\n")
    print(f"Wrote {OUT_HEADER}")


if __name__ == "__main__":
    main()
