#!/usr/bin/env python3
"""Emit src/gen/archetypes_gen.h — the C++ mirror of the archetype metadata.

The observation's matchup tail (value-bucket index + the two archetype one-hots)
is appended Python-side by train/env.py, but the in-process AlphaZero actor
(bin/az_actor, src/actor/obs_builder.cpp) rebuilds the SAME observation in C++ and
must therefore produce a byte-identical tail. Rather than duplicate the deck ->
archetype table there, this generator bakes it into a header at build time, so
train/archetypes.py + bin/resources/decks/archetypes.json stay the single source
of truth for both sides (same pattern as train/gen_card_costs.py ->
src/gen/card_costs_gen.h).

Emits DATA only (the archetype names, the constants, and the deck -> index
table); the deck-name normalization and lookup logic live in the consumer
(src/actor/obs_builder.cpp), mirroring archetypes.normalize_deck.

Run via `make pygen` (the default build) or directly:
    train/.venv/bin/python train/gen_archetypes.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import archetypes  # noqa: E402
from gen_util import write_if_changed  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_HEADER = os.path.join(REPO_ROOT, "src/gen/archetypes_gen.h")


def main():
    mapping = archetypes.mapping()          # normalized stem -> archetype name
    hdr = [
        "// AUTO-GENERATED by train/gen_archetypes.py — do not edit manually.",
        "// Inputs: train/archetypes.py (ARCHETYPES order), "
        "bin/resources/decks/archetypes.json",
        "// C++ mirror of the deck -> archetype -> value-bucket metadata, so the",
        "// in-process AZ actor's observation tail (src/actor/obs_builder.cpp) is",
        "// identical to the one train/env.py appends. Keys are already normalized",
        "// the way archetypes.normalize_deck() normalizes a deck spec: lowercase,",
        "// decks/-relative, no '.dk' suffix, '/' separators.",
        "#pragma once",
        "",
        "// Archetype slots: the tagged archetypes in ARCHETYPES order, then the",
        "// 'unknown' fallback bucket at index ARCH_UNKNOWN.",
        f"static const int ARCH_N = {archetypes.N_ARCH};",
        f"static const int ARCH_UNKNOWN = {archetypes.UNKNOWN};",
        "// Value buckets span (self archetype x opponent archetype).",
        f"static const int ARCH_N_VALUE_BUCKETS = {archetypes.N_VALUE_BUCKETS};",
        "",
        f"static const char* const ARCH_NAMES[{archetypes.N_ARCH}] = {{",
    ]
    for i, name in enumerate(archetypes.ARCHETYPES):
        hdr.append(f'    "{name}",  // {i}')
    hdr += [
        f'    "{archetypes.UNKNOWN_NAME}",  // {archetypes.UNKNOWN}',
        "};",
        "",
        "struct ArchDeckTag {",
        "    const char* stem;  // normalized decks/-relative stem",
        "    int arch;          // index into ARCH_NAMES",
        "};",
        "",
        f"static const int ARCH_N_DECK_TAGS = {len(mapping)};",
        f"static const ArchDeckTag ARCH_DECK_TAGS[{max(len(mapping), 1)}] = {{",
    ]
    if not mapping:
        # Keep the array non-empty (zero-sized arrays are not valid C++).
        hdr.append('    {"", ARCH_UNKNOWN},  // archetypes.json has no deck tags')
    for stem in sorted(mapping):
        arch = archetypes.ARCHETYPES.index(mapping[stem])
        hdr.append(f'    {{"{stem}", {arch}}},  // {mapping[stem]}')
    hdr += ["};", ""]

    write_if_changed(OUT_HEADER, "\n".join(hdr) + "\n")
    print(f"Wrote {OUT_HEADER}")


if __name__ == "__main__":
    main()
