#ifndef REPLACEMENT_EFFECTS_H
#define REPLACEMENT_EFFECTS_H

#include "../components/zone.h"
#include "../ecs/entity.h"

// Replacement-effect dispatcher (MTG Comprehensive Rules 614 / 616).
//
// A replacement effect (614) is a kind of continuous effect that watches a
// particular event and replaces it with a different event ("shields"). Unlike the
// 613 layer system (which timestamp-orders static abilities), replacement effects
// are not ordered: when more than one would modify the same event, the affected
// object's controller/owner chooses ONE to apply, then the process repeats with the
// remaining applicable effects (616.1 / 616.1f). A replacement effect gets only one
// opportunity per event (614.5).
//
// A ReplacementEvent is a small mutable description of an event that is *about to*
// happen. The caller fills in the input fields, calls dispatch(), then carries out
// the (possibly modified) outcome fields. Replacement effects may be generated by a
// static ability, a keyword (e.g. dredge), or a resolving spell/ability — the
// dispatcher does not care about the source, only the event.
struct ReplacementEvent {
    enum Type {
        ENTERS_BATTLEFIELD,  // a permanent is about to enter the battlefield
        MOVE_TO_ZONE,        // a card is about to change zones
        DRAW_CARD,           // a player is about to draw a card
        UNTAP,               // a permanent is about to untap during its controller's untap step
    };

    Type type;
    Entity entity = 0;                                 // affected object (drawing player entity for DRAW_CARD)
    Zone::Ownership affected_player = Zone::PLAYER_A;   // 616.1 chooser

    // ENTERS_BATTLEFIELD outcome
    bool enters_tapped = false;
    int  etb_p1p1 = 0;                                 // +1/+1 counters to add after the Creature component exists

    // MOVE_TO_ZONE in/out
    Zone::ZoneValue destination = Zone::GRAVEYARD;     // caller seeds the natural destination; dispatch may redirect

    // DRAW_CARD outcome (dredge, 702.52a / 614.1a)
    bool   draw_replaced = false;                      // a dredge replaced the draw — caller performs no draw
    Entity dredge_source = 0;                          // the dredge card to return from graveyard to hand
    int    dredge_mill = 0;                            // number of cards to mill for the dredge

    // UNTAP outcome (Choke, 614.1d)
    bool   skip_untap = false;                         // a replacement prevents this permanent from untapping
};

namespace replacement {
// Apply every applicable replacement effect to `ev` per rules 614/616, mutating its
// outcome fields in place. Prompts the affected player to choose one at a time when
// more than one applies (616.1).
void dispatch(ReplacementEvent &ev);
}

#endif /* REPLACEMENT_EFFECTS_H */
