#ifndef REPLACEMENT_EFFECTS_H
#define REPLACEMENT_EFFECTS_H

#include <cstddef>
#include <string>
#include <vector>

#include "../classes/action.h"
#include "../classes/colors.h"
#include "../components/zone.h"
#include "../ecs/entity.h"

// Replacement-effect dispatcher (MTG Comprehensive Rules 614 / 616).
//
// A replacement effect (614) is a kind of continuous effect that watches a
// particular event and replaces it with a different event ("shields"). Unlike the
// 613 layer system (which timestamp-orders static abilities), replacement effects
// are not ordered: when more than one would modify the same event, the affected
// object's controller/owner chooses ONE to apply, then the process repeats with the
// remaining applicable effects (616.1 / 616.1f). A replacement effect gets only one
// opportunity per event (614.5).
//
// A ReplacementEvent is a small mutable description of an event that is *about to*
// happen. The caller fills in the input fields, calls dispatch(), then carries out
// the (possibly modified) outcome fields. Replacement effects may be generated by a
// static ability, a keyword (e.g. dredge), or a resolving spell/ability — the
// dispatcher does not care about the source, only the event.
struct ReplacementEvent {
    enum Type {
        ENTERS_BATTLEFIELD,  // a permanent is about to enter the battlefield
        MOVE_TO_ZONE,        // a card is about to change zones
        DRAW_CARD,           // a player is about to draw a card
        UNTAP,               // a permanent is about to untap during its controller's untap step
        PRODUCE_MANA,        // a permanent is about to produce mana from being tapped (Damping Sphere)
    };

    Type type;
    Entity entity = 0;                                 // affected object (drawing player entity for DRAW_CARD)
    Zone::Ownership affected_player = Zone::PLAYER_A;   // 616.1 chooser

    // ENTERS_BATTLEFIELD outcome
    bool enters_tapped = false;
    int  etb_p1p1 = 0;                                 // counters to add when the permanent enters (614.1c); count of etb_counter_type
    std::string etb_counter_type = "P1P1";             // kind of "enters with" counter ("P1P1", "CHARGE", ...)

    // MOVE_TO_ZONE in/out
    Zone::ZoneValue destination = Zone::GRAVEYARD;     // caller seeds the natural destination; dispatch may redirect
    Zone::ZoneValue origin = Zone::LIBRARY;            // caller seeds the zone the card is leaving
    bool prevented = false;                            // 614.13/CantHappen — the move doesn't happen; the card stays in its origin zone (Grafdigger's Cage)

    // DRAW_CARD outcome (dredge, 702.52a / 614.1a)
    bool   draw_replaced = false;                      // a dredge replaced the draw — caller performs no draw
    Entity dredge_source = 0;                          // the dredge card to return from graveyard to hand
    int    dredge_mill = 0;                            // number of cards to mill for the dredge

    // UNTAP outcome (Choke, 614.1d)
    bool   skip_untap = false;                         // a replacement prevents this permanent from untapping

    // PRODUCE_MANA in/out (Damping Sphere, 614.1). Caller seeds the producing permanent (entity),
    // its controller (affected_player), the color it would produce and how much. dispatch() may
    // rewrite produced_color (e.g. to {C}) and sets mana_replaced; the caller adds produced_amount
    // mana of the (possibly replaced) color to the pool.
    Colors produced_color = COLORLESS;                 // input: color the source would produce; dispatch may replace it
    size_t produced_amount = 0;                        // input: amount of mana produced this tap
    bool   mana_replaced = false;                      // output: a ProduceMana replacement rewrote the production (idempotency guard)
};

namespace replacement {
// Apply every applicable replacement effect to `ev` per rules 614/616, mutating its
// outcome fields in place. Prompts the affected player to choose one at a time when
// more than one applies (616.1).
void dispatch(ReplacementEvent &ev);

// One dredge candidate behind a draw-replacement menu entry (menu index i+1).
struct DrawReplacementOption {
    Entity source = 0;  // the dredge card in the graveyard
    int mill = 0;       // its dredge number (cards to mill)
};

// Build the dredge draw-replacement menu for a draw by `player` (CR 702.52a):
// menu[0] is always "Draw a card"; menu[i > 0] corresponds to (*opts)[i - 1].
// Returns an EMPTY menu when no dredge applies — the promptless common case.
// Pure ECS reads (graveyard scan + library count), so a suspended prompt
// re-derives the identical menu on resume. Shared by the blocking
// dispatch(DRAW_CARD) path, the turn-based draw batch (resume_pending_draws)
// and the suspendable resolution-time draw loop (effects
// draw_n_with_replacements).
std::vector<LegalAction> collect_draw_replacements(Zone::Ownership player,
                                                   std::vector<DrawReplacementOption> *opts);

// Diagnostics: how many 616.1 choose-one-of-several-replacements prompts this
// process has emitted. The choose_one prompt is the one remaining blocking
// mid-flow prompt family (see the residual note at choose_one in
// replacement_effects.cpp); this counter quantifies its reachability in any
// measurement run.
size_t choose_one_prompt_count();
}

#endif /* REPLACEMENT_EFFECTS_H */
