#ifndef RULES_MODIFYING_H
#define RULES_MODIFYING_H

#include "../ecs/entity.h"
#include "../components/zone.h"

struct CardData;

// Prohibition / permission continuous effects generated by static abilities (the casting,
// activating, and land-play rules; rule 613.11 rules-modifiers). Unlike characteristic
// effects (the 613 seven-layer pipeline), these don't change an object's characteristics —
// they modify what the rules allow — so they are queried at the relevant decision sites
// rather than applied in a layer. Collected here so each prohibition is a single query and
// all uniformly honor ActiveStatic::suppressed (an ability-removal effect such as Humility,
// rule 613.1f). Each scans the g_active_statics cache that gather_active_statics rebuilds
// every state-based-effects pass.
namespace rules_mod {

// CantBeActivated (Null Rod, Collector Ouphe, Disruptor Flute). `activation_prohibited` is
// the general check for a permanent's non-mana activated abilities (artifact filter +
// Disruptor Flute NamedCard). `mana_activation_prohibited` is the mana-ability variant: it
// ignores NamedCard prohibitions, since Disruptor Flute's restriction excludes mana
// abilities (ValidSA$ Activated.!ManaAbility).
bool activation_prohibited(Entity permanent);
bool mana_activation_prohibited(Entity permanent);

// CantBeCast: may `caster` not cast `card` right now? The spell's printed characteristics are
// read from `card` (its type line short-circuits the nonCreature filter; its mana value and
// {X}-cost flag drive the characteristic-based prohibitions — Gaddock Teeg). `cast_from` is the
// zone the spell is being cast from (HAND for a normal cast, GRAVEYARD for flashback, etc.) — an
// Origin$-restricted static (Grafdigger's Cage: graveyard/library) applies only when `cast_from`
// matches.
bool cast_prohibited(Zone::Ownership caster, const CardData &card,
                     Zone::ZoneValue cast_from = Zone::HAND);

// Opponent sorcery-speed lock (Teferi, Time Raveler's static "Each opponent can cast spells only
// any time they could cast a sorcery"): is `caster` currently forced to cast at sorcery speed by an
// active OnlySorcerySpeed$ CantBeCast static an opponent controls? When true the cast-speed gate
// requires the sorcery-speed timing window (the caster's turn, a main phase, empty stack) for EVERY
// spell the caster casts — even instants/flash — regardless of the spell's own type (CR 601.3a).
// This is NOT a prohibition (cast_prohibited ignores the static); it is a timing restriction applied
// on top of the normal instant-speed check.
bool opponent_sorcery_speed_locked(Zone::Ownership caster);

// Cast-with-flash permission (Teferi, Time Raveler's +1 "you may cast sorcery spells as though they
// had flash"): may `caster` cast `card` as though it had flash right now? True when an active
// cur_game.cast_with_flash_permissions entry owned by `caster` covers the spell (its ValidCard$
// filter matches, e.g. "Sorcery"). Lifts the sorcery-speed timing restriction for a matching spell
// (CR 702.8). An opponent sorcery-speed lock, if also active against the caster, still overrides
// this (the lock is applied after in the gate).
bool cast_with_flash_active(Zone::Ownership caster, const CardData &card);

// CantAttack (Ensnaring Bridge): may the creature `creature` NOT be declared as an attacker
// right now (CR 509.1a)? True when any active CantAttack static's ValidCard$ filter matches it.
// A dynamic power/toughness-vs-X qualifier (Ensnaring Bridge's Creature.powerGTX, "power greater
// than the number of cards in your hand") is evaluated with X = the static SOURCE's controller's
// hand size — so "your hand" is the Bridge controller's hand, applied to every creature. Only the
// blanket form (no Target$ player restriction) is honoured. Queried in declare_attackers so a
// prohibited creature is never offered as a legal attacker.
bool attack_prohibited(Entity creature);

// AdjustLandPlays / MayPlay (Icetill Explorer), evaluated for `player`.
int  land_play_bonus(Zone::Ownership player);
bool may_play_lands_from_graveyard(Zone::Ownership player);

// How many lands `player` may still play this turn (CR 305.2 plus AdjustLandPlays
// statics), clamped at 0 — `land_play_limit` is the per-turn allowance (1 + bonus),
// `land_drops_remaining` that allowance minus Player::lands_played_this_turn. THE
// shared expression behind every "may I play a land?" gate: the PLAY_LAND legal-action
// enumeration (hand and impulse-exile), and the ML observation's mana-development
// block, which must report exactly what the menu will offer. Returns 0 for a player
// whose Player component is missing.
int  land_play_limit(Zone::Ownership player);
int  land_drops_remaining(Zone::Ownership player);

// DisableTriggers (Doorkeeper Thrull): are an entering permanent's ETB triggers suppressed
// because its card type matches an active DisableTriggers cause? The caller guards that the
// event is a card changing zone onto the battlefield.
bool etb_triggers_suppressed(Entity entering);

}

#endif /* RULES_MODIFYING_H */
