#ifndef RULES_MODIFYING_H
#define RULES_MODIFYING_H

#include "../ecs/entity.h"
#include "../components/zone.h"

struct CardData;

// Prohibition / permission continuous effects generated by static abilities (the casting,
// activating, and land-play rules; rule 613.11 rules-modifiers). Unlike characteristic
// effects (the 613 seven-layer pipeline), these don't change an object's characteristics —
// they modify what the rules allow — so they are queried at the relevant decision sites
// rather than applied in a layer. Collected here so each prohibition is a single query and
// all uniformly honor ActiveStatic::suppressed (an ability-removal effect such as Humility,
// rule 613.1f). Each scans the g_active_statics cache that gather_active_statics rebuilds
// every state-based-effects pass.
namespace rules_mod {

// CantBeActivated (Null Rod, Collector Ouphe, Disruptor Flute). `activation_prohibited` is
// the general check for a permanent's non-mana activated abilities (artifact filter +
// Disruptor Flute NamedCard). `mana_activation_prohibited` is the mana-ability variant: it
// ignores NamedCard prohibitions, since Disruptor Flute's restriction excludes mana
// abilities (ValidSA$ Activated.!ManaAbility).
bool activation_prohibited(Entity permanent);
bool mana_activation_prohibited(Entity permanent);

// CantBeCast: may `caster` not cast a spell right now? `card_is_creature` short-circuits the
// nonCreature filter (per-turn noncreature limit). `cast_from` is the zone the spell is being
// cast from (HAND for a normal cast, GRAVEYARD for flashback, etc.) — an Origin$-restricted
// static (Grafdigger's Cage: graveyard/library) applies only when `cast_from` matches.
bool cast_prohibited(Zone::Ownership caster, bool card_is_creature,
                     Zone::ZoneValue cast_from = Zone::HAND);

// AdjustLandPlays / MayPlay (Icetill Explorer), evaluated for `player`.
int  land_play_bonus(Zone::Ownership player);
bool may_play_lands_from_graveyard(Zone::Ownership player);

// DisableTriggers (Doorkeeper Thrull): are an entering permanent's ETB triggers suppressed
// because its card type matches an active DisableTriggers cause? The caller guards that the
// event is a card changing zone onto the battlefield.
bool etb_triggers_suppressed(Entity entering);

}

#endif /* RULES_MODIFYING_H */
